id: IC0CDA8FB
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:27:32.574786
last_modified: 2023-01-04 11:27:32.574803
source_metadata:
  collections:
  - Adzom Gyalse Series
  - Works of Tibetan Masters
bases:
  4B24:
    title: 'Advice for Beginners: How to Overcome Obstacles to Meditation'
    base_file: 4B24.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
